Update mongodb.rb
Just ran into this upon upgrading to 1.0.1 but am not sure how it ever worked. 
```chef (12.21.1)>  mongo_port = node['mongodb']['config']['net']['port']
NoMethodError: undefined method `[]' for nil:NilClass
chef (12.21.1)>  mongo_port = node['mongodb']['config'].keys
 => ["mongod", "mongos"]```